### PR TITLE
Fixed a NullPointerException when displaying SUI message boxes

### LINKED ISSUE #1568: SUI message box windows no longer display
One or more regressions in SUI windows have been introduced, where they don't appear to the player.

Example of the newbie quest being granted when spawning:

```
29-06-24 15:06:01.095 T: [QuestService] user/Venne Uthaxars received quest quest/c_newbie_start
29-06-24 15:06:01.096 T: [QuestService] user/Venne Uthaxars activating task 0 of quest quest/c_newbie_start
29-06-24 15:06:01.110 E: Fatal Exception while processing intent: SuiWindowIntent(player=Player[226295 NAME=user / Venne Uthaxars STATE=ZONED_IN], window=com.projectswg.holocore.resources.support.global.zone.sui.SuiMessageBox@3f735f22, windowId=-1, event=NEW)
29-06-24 15:06:01.110 E: Exception in thread "intent-processor-8" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
29-06-24 15:06:01.110 E: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
29-06-24 15:06:01.110 E:     me.joshlarson.jlcommon.control.Service.invoke(Service.java:135)
29-06-24 15:06:01.110 E:     me.joshlarson.jlcommon.control.Service.lambda$registerIntentHandlers$1(Service.java:119)
29-06-24 15:06:01.110 E:     me.joshlarson.jlcommon.control.IntentManager$IntentRunner.broadcast(IntentManager.java:214)
29-06-24 15:06:01.110 E:     me.joshlarson.jlcommon.control.IntentManager$IntentExecutor.run(IntentManager.java:269)
29-06-24 15:06:01.110 E:     me.joshlarson.jlcommon.utilities.ThreadUtilities.safeRun(ThreadUtilities.java:47)
29-06-24 15:06:01.110 E:     me.joshlarson.jlcommon.concurrency.ThreadPool$ThreadExecutor.threadExecutor(ThreadPool.java:174)
29-06-24 15:06:01.110 E:     java.base/java.lang.Thread.run(Thread.java:1583)
29-06-24 15:06:01.110 E:   Exception in thread "intent-processor-8" java.lang.reflect.InvocationTargetException: null
29-06-24 15:06:01.111 E:   Caused by: java.lang.reflect.InvocationTargetException: null
29-06-24 15:06:01.111 E:       java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:115)
29-06-24 15:06:01.111 E:       java.base/java.lang.reflect.Method.invoke(Method.java:580)
29-06-24 15:06:01.111 E:       me.joshlarson.jlcommon.control.Service.invoke(Service.java:133)
29-06-24 15:06:01.111 E:       me.joshlarson.jlcommon.control.Service.lambda$registerIntentHandlers$1(Service.java:119)
29-06-24 15:06:01.111 E:       me.joshlarson.jlcommon.control.IntentManager$IntentRunner.broadcast(IntentManager.java:214)
29-06-24 15:06:01.111 E:       me.joshlarson.jlcommon.control.IntentManager$IntentExecutor.run(IntentManager.java:269)
29-06-24 15:06:01.111 E:       me.joshlarson.jlcommon.utilities.ThreadUtilities.safeRun(ThreadUtilities.java:47)
29-06-24 15:06:01.111 E:       me.joshlarson.jlcommon.concurrency.ThreadPool$ThreadExecutor.threadExecutor(ThreadPool.java:174)
29-06-24 15:06:01.111 E:       java.base/java.lang.Thread.run(Thread.java:1583)
29-06-24 15:06:01.111 E:     Exception in thread "intent-processor-8" java.lang.NullPointerException: null
29-06-24 15:06:01.111 E:     Caused by: java.lang.NullPointerException: null
29-06-24 15:06:01.111 E:         com.projectswg.common.data.sui.SuiBaseWindow.getLength(SuiBaseWindow.kt:240)
29-06-24 15:06:01.111 E:         com.projectswg.common.network.packets.swg.zone.server_ui.SuiCreatePageMessage.encode(SuiCreatePageMessage.java:58)
29-06-24 15:06:01.112 E:         com.projectswg.holocore.resources.support.global.network.NetworkClient.addToOutbound(NetworkClient.kt:215)
29-06-24 15:06:01.112 E:         com.projectswg.holocore.resources.support.global.network.NetworkClient.player$lambda$2(NetworkClient.kt:77)
29-06-24 15:06:01.112 E:         com.projectswg.holocore.resources.support.global.player.Player.sendPacket(Player.java:168)
29-06-24 15:06:01.112 E:         com.projectswg.holocore.services.support.global.zone.sui.SuiService.displayWindow(SuiService.kt:106)
29-06-24 15:06:01.112 E:         com.projectswg.holocore.services.support.global.zone.sui.SuiService.handleSuiWindowIntent(SuiService.kt:56)
29-06-24 15:06:01.112 E:         java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
29-06-24 15:06:01.112 E:         java.base/java.lang.reflect.Method.invoke(Method.java:580)
29-06-24 15:06:01.112 E:         me.joshlarson.jlcommon.control.Service.invoke(Service.java:133)
29-06-24 15:06:01.112 E:         me.joshlarson.jlcommon.control.Service.lambda$registerIntentHandlers$1(Service.java:119)
29-06-24 15:06:01.112 E:         me.joshlarson.jlcommon.control.IntentManager$IntentRunner.broadcast(IntentManager.java:214)
29-06-24 15:06:01.112 E:         me.joshlarson.jlcommon.control.IntentManager$IntentExecutor.run(IntentManager.java:269)
29-06-24 15:06:01.112 E:         me.joshlarson.jlcommon.utilities.ThreadUtilities.safeRun(ThreadUtilities.java:47)
29-06-24 15:06:01.112 E:         me.joshlarson.jlcommon.concurrency.ThreadPool$ThreadExecutor.threadExecutor(ThreadPool.java:174)
29-06-24 15:06:01.112 E:         java.base/java.lang.Thread.run(Thread.java:1583)
```

### PR DESCRIPTION
**Pull request by madsboddum**
Fixes #1568.

I was able to reproduce the problem with our existing automated tests by simply introducing packet encoding and decoding in this commit: b7139af3de1d0f31c79f615dbc1bfcfe3b133ecb

The result isn't used for anything, although I think that would be cool to add in later for tests that give even more confidence.

The actual fix is here: b7139af3de1d0f31c79f615dbc1bfcfe3b133ecb

### CODE REVIEW

File: src/test/java/com/projectswg/holocore/test/resources/GenericPlayer.java [hunk 1]
```diff
@@ -82,14 +83,24 @@ public GenericPlayer() {
...
 			packetLock.unlock();
 		}
 		handlePacket(packet);
 	}
-	
+
+	private static void encodeAndDecode(SWGPacket packet) {
+		try {
+			// This doesn't actually test the encoding and decoding of the packet, but it does test that the packet can be encoded and decoded without throwing an exception
+			NetworkProtocol.decode(NetworkProtocol.encode(packet));
```
Comment (Josh-Larson) [inline src/test/java/com/projectswg/holocore/test/resources/GenericPlayer.java:98]: The way to see if it was decoded properly is to check the netbuffer index after parsing--it should be the end of the buffer

Comment (madsboddum) [reply src/test/java/com/projectswg/holocore/test/resources/GenericPlayer.java:98]: I've prepared a patch for this - the method looks like this now.

```kt
private static void encodeAndDecode(SWGPacket packet) {
	try {
		// This doesn't actually test the encoding and decoding of the packet, but it does test that the packet can be encoded and decoded without throwing an exception
		NetBuffer data = NetworkProtocol.encode(packet);
		NetworkProtocol.decode(data);
		int remaining = data.remaining();
		if (remaining > 0) {
			throw new RuntimeException("Encoded packet buffer had more data that wasn't read during decoding. Bytes remaining: " + remaining);
		}
	} catch (Throwable t) {
		throw new RuntimeException("Failed to encode and decode packet", t);
	}
}
```
