### PR TITLE
Fixed exploration badges

### LINKED ISSUE #1455: [Badge] Exploration badge throwing errors
2023-12-04_01h24_19

Error popping up near waypoint Tatooine 6646 21 4220
Apparently something about exploration badges not working correctly

### PR DESCRIPTION
**Pull request by madsboddum**
Fixes #1455

I added teleportation handling in `ExplorationBadgeService`, so our tests wouldn't have to actually move the character around with data transforms. I tried going down the movement route, but it was quite complex and didn't really seem worth it after a couple of hours.
I figured this wouldn't hurt to have during real gameplay either.

The added test failed before fixing the problems in `ExplorationBadgeLoader` and passed after.

### CODE REVIEW

File: src/main/java/com/projectswg/holocore/services/gameplay/player/badge/ExplorationBadgeService.kt [hunk 1]
```diff
@@ -46,6 +47,19 @@ class ExplorationBadgeService : Service() {
 			GrantBadgeIntent.broadcast(creatureObject, explorationBadgeInfo.badgeName)
 		}
 	}
+	@IntentHandler
+	private fun handleObjectTeleportedIntent(pti: ObjectTeleportIntent) {
+		if (pti.`object` !is CreatureObject)
+			return
+		val creatureObject = pti.`object` as CreatureObject
```
Comment (Josh-Larson) [inline src/main/java/com/projectswg/holocore/services/gameplay/player/badge/ExplorationBadgeService.kt:54]: This can be:
```
val createObject = pti.`object` as? CreatureObject ?: return
```

Comment (Josh-Larson) [reply src/main/java/com/projectswg/holocore/services/gameplay/player/badge/ExplorationBadgeService.kt:54]: I also think there's a typo in the intent name, I think you meant `oti`

Comment (madsboddum) [reply src/main/java/com/projectswg/holocore/services/gameplay/player/badge/ExplorationBadgeService.kt:54]: My bad, copy-paste is strong in this one!

Comment (madsboddum) [reply src/main/java/com/projectswg/holocore/services/gameplay/player/badge/ExplorationBadgeService.kt]: I've fixed the typo and shortened the `null` handling as suggested.

Comment (Josh-Larson) [reply src/main/java/com/projectswg/holocore/services/gameplay/player/badge/ExplorationBadgeService.kt]: It also replaces the if check right above it. `as?` is meant for this situation where you want a particular type and Kotlin will convert it if it can, otherwise it'll be null--triggering the return

Comment (madsboddum) [reply src/main/java/com/projectswg/holocore/services/gameplay/player/badge/ExplorationBadgeService.kt]: I have no explanation for what happened there 😅 
I have removed the if statement.
